on:
  push:
    branches:
    - master
  pull_request:

name: CI

jobs:
  GitBook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Generate SUMMARY
        run: |
          npm init -f
          npm install gitbook-summary
          npx book sm -t "[Redis 英文文档](https://github.com/antirez/redis-doc)" -i node_modules
          rm -rf node_modules package.json package-lock.json
          echo "# [redis.io](https://redis.io/)" > README.md
          ls -la
      - name: Upload SUMMARY
        run: |
          git config user.name "Kang Huaishuai"
          git config user.email khs1994@khs1994.com
          git add SUMMARY.md
          git commit -m "Update SUMMARY.md" -s
          git -c http.extraheader="AUTHORIZATION: basic ${GITHUB_TOKEN}" push origin $(git rev-parse --short HEAD):master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'push'  
      - name: gitbook-build
        uses: docker://khs1994/gitbook
      - name: gitbook-deploy
        if: github.event_name == 'push'
        uses: docker://khs1994/gitbook
        with:
          args: deploy
        env:
          GIT_USERNAME: "khs1994"
          GIT_USEREMAIL: "khs1994@khs1994.com"
          GIT_BRANCH: "gh-pages"
          GITHUB_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
